[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.0
    olikraus/U8g2@^2.35.7
    robtillaart/SHT2x@^0.5.0
    Wire
build_flags = 
    -I../../common
    -DBOARD_HAS_PSRAM
    -DCONFIG_ESP_RMAKER_TASK_STACK=4096
board_build.partitions = rainmaker.csv
